"use client";
import { useState } from "react";
import Link from "next/link";
import { askLibrarian } from "@/lib/api";

export default function AssistantPage() {
  const [question, setQuestion] = useState(""); const [messages, setMessages] = useState<Array<{ question: string; answer: string; references: Array<{ id: string; title: string; creators: string[]; availableCopies: number }> }>>([]); const [busy, setBusy] = useState(false);
  return <div className="max-w-2xl"><h1 className="font-serif text-[28px]">Ask the Librarian</h1><p className="mt-1 text-[11px] text-ink-muted">Answers are grounded in the live catalog.</p><div className="mt-7 space-y-4">{messages.map((message, index) => <div key={index}><div className="ml-auto max-w-[78%] bg-stacks px-4 py-3 text-[12px] leading-5 text-stacks-text">{message.question}</div><div className="mt-3 max-w-[78%] border border-paper-line bg-paper-alt px-4 py-3 text-[12px] leading-5">{message.answer}{message.references.map((reference) => <Link key={reference.id} href={`/catalog/item?id=${reference.id}`} className="mt-3 block border border-paper-line bg-paper px-3 py-2 text-[11px]"><span className="text-ink-muted">{reference.availableCopies} on shelf</span> - {reference.title}</Link>)}</div></div>)}</div><form className="mt-7 flex gap-3 border-t border-paper-line pt-4" onSubmit={async (event) => { event.preventDefault(); if (!question.trim()) return; setBusy(true); try { const result = await askLibrarian(question); setMessages((current) => [...current, { question, ...result }]); setQuestion(""); } finally { setBusy(false); } }}><input value={question} onChange={(event) => setQuestion(event.target.value)} className="underline-input flex-1" placeholder="Ask about a title, author, or subject" /><button className="stamp-button" disabled={busy}>{busy ? "Searching..." : "Ask"}</button></form></div>;
}
